### ISSUE TITLE
Request for Dataset Access

### ISSUE THREAD

**Issue by magical-cao** [jxh4945777/ChatEA#1]
I hope this message finds you well.

I came across your impressive project on GitHub and noticed the related dataset used in your work. I am currently working on a similar research and would greatly benefit from accessing the icews-wiki and icews-yago dataset for my analysis and experiments.

Could you kindly share the dataset or guide me on how I could access it? I assure you that it will be used solely for academic and research purposes.

Thank you for your time and consideration. I look forward to your response.

**Comment by jxh4945777** [comment]
Thank you for your interest in our project! We’re glad to hear that it could be helpful for your research.

You can access the datasets through this link: https://github.com/jxh4945777/Simple-HHEA.

Best of luck with your work, and feel free to reach out if you have any further questions.

**Comment by magical-cao** [comment]
thanks for your answer. I get the datasets successfully!
